openapi: 3.2.0
info:
  title: Worldline FIDO server Token Resource API
  version: 1.0.0
  contact:
    email: dl-ita-fido-server-sm@worldline.com
servers:
- url: https://fido.worldline-solutions.com
tags:
- name: Token Resource
paths:
  /oauth2/token:
    post:
      servers:
      - url: https://access.fido.worldline-solutions.com
      summary: Get access token
      tags:
      - Token Resource
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - grant_type
              - audience
              type: object
              properties:
                grant_type:
                  minLength: 1
                  pattern: client_credentials
                  type: string
                audience:
                  minLength: 1
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenDTO'
        '403':
          description: Not Allowed
        '401':
          description: Not Authorized
components:
  schemas:
    AccessTokenDTO:
      type: object
      properties:
        access_token:
          type: string
        expires_in:
          format: int32
          type: integer
